### PR TITLE
add requirements.txt

### PR DESCRIPTION
**Pull request by tekumara**

### CODE REVIEW

**Comment by four43** [comment]
This project has a conda environment file, but I can add a requirements.txt. It seems like this has way more than needed though. Why's that?

**Comment by four43** [comment]
This project has a conda environment file, but I can add a requirements.txt. It seems like this has way more than needed though. Why's that? Are those pinned sub dependencies?

**Comment by tekumara** [comment]
It's for those not using conda, as well as pinning the versions. `pip freeze > requirements.txt` does include transitive dependencies.

**Comment by tekumara** [comment]
No response so closing this.

**Comment by four43** [comment]
I am so sorry I totally dropped the ball on this. I'm much less of a python newb and understand this ecosystem better.

**Comment by four43** [comment]
@tekumara - I added the files for Pipenv in 0337325 (Python's preferred package manager now) and hopefully this solves your use case. Thanks for the tip!

**Comment by tekumara** [comment]
Cool! Thanks. I've had a few problems with pipenv myself, and think `pip` and `requirement.txt` is equally preferred to pipenv by some.

**Pull request closed without merging**
